apiVersion: v1
kind: Service
metadata:
  name: jetson-exporter
  namespace: monitoring
  labels:
    app: jetson-exporter
spec:
  selector:
    app: jetson-exporter
  ports:
    - name: metrics
      port: 9101
      targetPort: 9101
