{
 "title": "K8s Cluster Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(irate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[5s])) / count(node_cpu_seconds_total{mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "MasterNode CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(irate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=\"155.230.16.159:9100\"}[5s])) / count(node_cpu_seconds_total{mode=\"idle\", instance=\"155.230.16.159:9100\"})"
    }
   ]
  },
  {
   "title": "Orin1 CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.217:9101\", statistic=\"val\"}"
    }
   ]
  },
  {
   "title": "Orin2 CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\"}"
    }
   ]
  },
  {
   "title": "Orin1 per Core Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\", core=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\", core=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\", core=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\", core=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\", core=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\", core=\"5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orin2 per Core Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\", core=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\", core=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\", core=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\", core=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\", core=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - cpu_Hz{instance=\"10.244.1.234:9101\", statistic=\"val\", core=\"5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[5s]))"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=\"155.230.16.159:9100\"}[5s]))"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\", instance=\"155.230.16.159:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=\"192.168.0.131:9100\"}[30s]))"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=\"192.168.0.131:9100\", mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=\"192.168.0.131:9100\"}[5s])) + 0.03"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=\"192.168.0.131:9100\", mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Cluster GPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(nvidia_smi_utilization_gpu_ratio{instance=\"155.230.16.159:9835\"}) + sum(gpu_usage_percentage_percent))/3"
    }
   ]
  },
  {
   "title": "MasterNode GPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio"
    }
   ]
  },
  {
   "title": "Orin1 GPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_usage_percentage_percent{instance=\"10.244.1.174:9101\"}"
    }
   ]
  },
  {
   "title": "Orin2 GPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_usage_percentage_percent{instance=\"10.244.1.234:9101\"}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)/ sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 1, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)"
    }
   ]
  },
  {
   "title": "MasterNode Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"155.230.16.159:9100\"} - node_memory_MemAvailable_bytes{instance=\"155.230.16.159:9100\"}) / node_memory_MemTotal_bytes{instance=\"155.230.16.159:9100\"} * 100"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 1, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"155.230.16.159:9100\"} - node_memory_MemAvailable_bytes{instance=\"155.230.16.159:9100\"}"
    }
   ]
  },
  {
   "title": "Orin1 Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ram_kB{statistic=\"used\", instance=\"10.244.1.174:9101\"} * 100) / ignoring(statistic) ram_kB{statistic=\"total\", instance=\"10.244.1.174:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 1, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ram_kB{statistic=\"used\", instance=\"10.244.1.234:9101\"}"
    }
   ]
  },
  {
   "title": "Orin2 Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ram_kB{statistic=\"used\", instance=\"10.244.1.234:9101\"} * 100) / ignoring(statistic) ram_kB{statistic=\"total\", instance=\"10.244.1.234:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 1, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ram_kB{statistic=\"used\", instance=\"10.244.1.234:9101\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"155.230.16.159:9100\"} - node_memory_MemAvailable_bytes{instance=\"155.230.16.159:9100\"}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"155.230.16.159:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ram_kB{statistic=\"used\", instance=\"10.244.1.174:9101\"}"
    },
    {
     "expr": "ram_kB{statistic=\"total\", instance=\"10.244.1.234:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ram_kB{statistic=\"used\", instance=\"10.244.1.234:9101\"}"
    },
    {
     "expr": "ram_kB{statistic=\"total\", instance=\"10.244.1.234:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"155.230.16.159:9100\", device=\"enp4s0\"}[5s]) * 8",
     "legendFormat": "Master Node"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"192.168.0.131:9100\", device=\"enP8p1s0\"}[5s]) * 8",
     "legendFormat": "orin1"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"192.168.0.3:9100\", device=\"enP8p1s0\"}[5s]) * 8",
     "legendFormat": "orin2"
    }
   ]
  },
  {
   "title": "MasterNode Recieved Byte",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"155.230.16.159:9100\", device=\"enp4s0\"}[5s]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orin1 Recieved Byte",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"192.168.0.131:9100\", device=\"enP8p1s0\"}[5s]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orin2 Recieved Byte",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"192.168.0.131:9100\", device=\"enP8p1s0\"}[5s]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"155.230.16.159:9100\", device=\"enp4s0\"}[5s]) * 8",
     "legendFormat": "Master Node"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"192.168.0.131:9100\", device=\"enP8p1s0\"}[5s]) * 8",
     "legendFormat": "orin1"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"192.168.0.3:9100\", device=\"enP8p1s0\"}[5s]) * 8",
     "legendFormat": "orin2"
    }
   ]
  },
  {
   "title": "MasterNode Transmit Byte",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"155.230.16.159:9100\", device=\"enp4s0\"}[5s]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orin1 Transmit Byte",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"192.168.0.131:9100\", device=\"enP8p1s0\"}[5s]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orin2 Transmit Byte",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"192.168.0.131:9100\", device=\"enP8p1s0\"}[5s]) * 8",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}